.TH "Imgs" 3 "Wed Aug 22 2018" "Version 1.1" "Lazer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Imgs \- С помощью этих функций можно проверить калибровку и шаговики\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDrawGitHubLogo\fP (int Speed)"
.br
.ti -1c
.RI "void \fBDrawSquare\fP (int StartX, int StartY, int EndX, int EndY, float Drspeed)"
.br
.in -1c
.SH "Detailed Description"
.PP 
С помощью этих функций можно проверить калибровку и шаговики\&. 


.SH "Function Documentation"
.PP 
.SS "void DrawGitHubLogo (int Speed)"
Двигает лазер так, что получается логотип GitHub\&. 
.PP
\fBParameters:\fP
.RS 4
\fISpeed\fP Скорость отрисовки My GitHub 
.RE
.PP

.SS "void DrawSquare (int StartX, int StartY, int EndX, int EndY, float Drspeed)"
Рисует квадрат по координатам\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Начальная координата по оси X 
.br
\fIStartY\fP Начальная координата по оси Y 
.br
\fIEndX\fP Конечная координата по оси X 
.br
\fIEndY\fP Конечная координата по оси Y 
.br
\fIDrspeed\fP Скорость 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazer from the source code\&.
