.TH "Numbers" 3 "Wed Aug 22 2018" "Version 1.1" "Lazer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Numbers \- С помощью этих функций можно нарисовать чиселки! Координаты начинаются с нижнего левого угла\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDrawNumber1\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber2\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber3\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber4\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber5\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber6\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber7\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber8\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber9\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber0\fP (int StartX=5, int StartY=5)"
.br
.ti -1c
.RI "void \fBDrawNumber\fP (int Num, int StartX=5, int StartY=5)"
.br
.in -1c
.SH "Detailed Description"
.PP 
С помощью этих функций можно нарисовать чиселки! Координаты начинаются с нижнего левого угла\&. 


.SH "Function Documentation"
.PP 
.SS "void DrawNumber (int Num, int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается Num\&. 
.PP
\fBParameters:\fP
.RS 4
\fINum\fP От 0 до 9 
.br
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber0 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 0\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber1 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 1\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber2 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 2\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber3 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 3\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber4 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 4\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber5 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 5\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber6 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 6\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber7 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 7\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber8 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 8\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SS "void DrawNumber9 (int StartX = \fC5\fP, int StartY = \fC5\fP)"
Двигает лазер так, что получается 9\&. 
.PP
\fBParameters:\fP
.RS 4
\fIStartX\fP Координата по оси X 
.br
\fIStartY\fP Координата по оси Y 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Lazer from the source code\&.
